SELECT
  encounter_id   AS "Encounter ID",
  encounter_date AS "Encounter Date",
  zeir_id        AS "ZEIR ID",
  gender         AS "Gender",
  gender         AS "Date of Birth",
  mother_id      AS "Mother ID",
  child_hiv_expo AS "Child HIV Exposure",
  facility_name  AS "Facility Name",
  district_name  AS "District Name",
  province_name  AS "Province Name",
  provider_name  AS "Provider Name",
  visit_id       AS "Visit ID",
  child_weighed  AS "Child Weighed",
  child_weight   AS "Child Weight",
  z_score        AS "Z-score",
  bcg_1          AS "BCG",
  opv_0          AS "OPV0",
  opv_1          AS "OPV1",
  pcv_1          AS "PCV1",
  pentavalent_1  AS "Penta 1",
  rota_1         AS "Rota 1",
  opv_2          AS "OPV2",
  pcv_2          AS "PCV2",
  pentavalent_2  AS "Penta2",
  rota_2         AS "Rota 2",
  opv_3          AS "OPV3",
  pcv_3          AS "PCV3",
  pentavalent_3  AS "Penta 3",
  measles_1      AS "Measles 1",
  mr_1           AS "MR1",
  opv_4          AS "OPV4",
  measles_2      AS "Measles 2",
  mr_2           AS "MR2",
  bcg_2          AS "BCG2",
  vitamin_a      AS "Vitamin A",
  mebendezol     AS "Mebendezol",
  itn            AS "ITN"
FROM facility_encounters;