SELECT
﻿ ROW_NUMBER () OVER (ORDER BY encounter_id) AS "Encounter ID",
   encounter_date     AS "Encounter Date",
   zeir_id            AS "ZEIR ID",
   gender             AS "Gender",
   dob                AS "Date of Birth",
   mother_id          AS "Mother ID",
   child_hiv_expo     AS "Child HIV Exposure",
  fac_id        AS "Facility ID",
  fac_name      AS "Facility Name",
  district_id   AS "District ID",
  district_name AS "District Name",
  province_id   AS "Province ID",
  province_name AS "Province Name",
  provider_id   AS "Provider ID",
  provider_name AS "Provider Name",
﻿﻿DENSE_RANK() OVER(ORDER BY encounter_date,zeir_id,fac_id,provider_id) AS "Visit ID",
   child_weighed      AS " Child Weighed",
   child_weight       AS "Child Weight",
  z_score       AS "Z-score",
   BCG1,
   OPV0,
   OPV1,
   PCV1,
   Penta1             AS "Penta 1",
   Rota1              AS "Rota 1",
   OPV2,
   PCV2,
   Penta2             AS "Penta2",
   Rota2              AS "Rota 2",
   OPV3,
   PCV3,
   Penta3             AS "Penta 3",
   Measles1           AS "Measles 1",
   MR1,
   OPV4,
   Measles2           AS "Measles 2",
   MR2,
   BCG2,
   vitamin_a          AS "Vitamin A",
   mebendezol         AS "Mebendezol"
 FROM facility_encounter_report;
