-- Truncate the encounter flat table for new extract
TRUNCATE TABLE path_zambia_etl.facility_encounter_report_2;


INSERT INTO path_zambia_etl.facility_encounter_report_2(

 encounter_id,
  encounter_date ,
  person_id,
  zeir_id           ,
  gender             ,
  dob               ,
  mother_id         ,
  child_hiv_expo     ,
 fac_id       ,
  fac_name      ,
  district_id   ,
  district_name ,
  province_id  ,
 province_name ,
  provider_id  ,
  provider_name ,
  child_weighed     ,
  child_weight       ,
  z_score      ,
  BCG1,
  OPV0,
  OPV1,
  PCV1,
  Penta1             ,
  Rota1              ,
  OPV2,
  PCV2,
  Penta2             ,
  Rota2              ,
  OPV3,
  PCV3,
  Penta3             ,
  Measles1           ,
  MR1,
  OPV4,
  Measles2           ,
  MR2,
  BCG2,
  vitamin_a  ,
 mebendezol

)

  (SELECT
     max(encounter_id)  AS 'Encounter ID',
     encounter_date     AS 'Encounter Date',
     person_id,
     zeir_id            AS 'ZEIR ID',
     gender             AS 'Gender',
     dob                AS 'Date of Birth',
     mother_id          AS 'Mother ID',
     child_hiv_expo     AS 'Child HIV Exposure',
     max(fac_id)        AS 'Facility ID',
     max(fac_name)      AS 'Facility Name',
     max(district_id)   AS 'District ID',
     max(district_name) AS 'District Name',
     max(province_id)   AS 'Province ID',
     max(province_name) AS 'Province Name',
     max(provider_id)   AS 'Provider ID',
     max(provider_name) AS 'Provider Name',
     child_weighed      AS ' Child Weighed',
     child_weight       AS 'Child Weight',
     max(z_score)       AS 'Z-score',
     BCG1,
     OPV0,
     OPV1,
     PCV1,
     Penta1             AS 'Penta 1',
     Rota1              AS 'Rota 1',
     OPV2,
     PCV2,
     Penta2             AS 'Penta2',
     Rota2              AS 'Rota 2',
     OPV3,
     PCV3,
     Penta3             AS 'Penta 3',
     Measles1           AS 'Measles 1',
     MR1,
     OPV4,
     Measles2           AS 'Measles 2',
     MR2,
     BCG2,
     vitamin_a          AS 'Vitamin A',
     mebendezol         AS 'Mebendezol'
   FROM path_zambia_etl.facility_encounter_report
   WHERE child_weighed IS NOT NULL
   GROUP BY zeir_id, person_id, encounter_date, child_weight,
     gender, dob, mother_id, child_hiv_expo, child_weighed,
     BCG1, OPV0, OPV1, PCV1, Penta1, Rota1, OPV2, PCV2, Penta2, Rota2,
     OPV3, PCV3, Penta3, Measles1, MR1, OPV4, Measles2, MR2, BCG2, vitamin_a, mebendezol)

  UNION

  (SELECT
     max(encounter_id)  AS 'Encounter ID',
     encounter_date     AS 'Encounter Date',
     person_id,
     zeir_id            AS 'ZEIR ID',
     gender             AS 'Gender',
     dob                AS 'Date of Birth',
     mother_id          AS 'Mother ID',
     child_hiv_expo     AS 'Child HIV Exposure',
     max(fac_id)        AS 'Facility ID',
     max(fac_name)      AS 'Facility Name',
     max(district_id)   AS 'District ID',
     max(district_name) AS 'District Name',
     max(province_id)   AS 'Province ID',
     max(province_name) AS 'Province Name',
     max(provider_id)   AS 'Provider ID',
     max(provider_name) AS 'Provider Name',
     child_weighed      AS ' Child Weighed',
     child_weight       AS 'Child Weight',
     max(z_score)       AS 'Z-score',
     BCG1,
     OPV0,
     OPV1,
     PCV1,
     Penta1             AS 'Penta 1',
     Rota1              AS 'Rota 1',
     OPV2,
     PCV2,
     Penta2             AS 'Penta2',
     Rota2              AS 'Rota 2',
     OPV3,
     PCV3,
     Penta3             AS 'Penta 3',
     Measles1           AS 'Measles 1',
     MR1,
     OPV4,
     Measles2           AS 'Measles 2',
     MR2,
     BCG2,
     vitamin_a          AS 'Vitamin A',
     mebendezol         AS 'Mebendezol'
   FROM path_zambia_etl.facility_encounter_report
   WHERE BCG1 IS NOT NULL
   GROUP BY zeir_id, person_id, encounter_date, child_weight, gender, dob, mother_id, child_hiv_expo, child_weighed,
     BCG1, OPV0, OPV1, PCV1, Penta1, Rota1, OPV2, PCV2, Penta2, Rota2,
     OPV3, PCV3, Penta3, Measles1, MR1, OPV4, Measles2, MR2, BCG2, vitamin_a, mebendezol)

  UNION

  (SELECT
     max(encounter_id)  AS 'Encounter ID',
     encounter_date     AS 'Encounter Date',
     person_id,
     zeir_id            AS 'ZEIR ID',
     gender             AS 'Gender',
     dob                AS 'Date of Birth',
     mother_id          AS 'Mother ID',
     child_hiv_expo     AS 'Child HIV Exposure',
     max(fac_id)        AS 'Facility ID',
     max(fac_name)      AS 'Facility Name',
     max(district_id)   AS 'District ID',
     max(district_name) AS 'District Name',
     max(province_id)   AS 'Province ID',
     max(province_name) AS 'Province Name',
     max(provider_id)   AS 'Provider ID',
     max(provider_name) AS 'Provider Name',
     child_weighed      AS ' Child Weighed',
     child_weight       AS 'Child Weight',
     max(z_score)       AS 'Z-score',
     BCG1,
     OPV0,
     OPV1,
     PCV1,
     Penta1             AS 'Penta 1',
     Rota1              AS 'Rota 1',
     OPV2,
     PCV2,
     Penta2             AS 'Penta2',
     Rota2              AS 'Rota 2',
     OPV3,
     PCV3,
     Penta3             AS 'Penta 3',
     Measles1           AS 'Measles 1',
     MR1,
     OPV4,
     Measles2           AS 'Measles 2',
     MR2,
     BCG2,
     vitamin_a          AS 'Vitamin A',
     mebendezol         AS 'Mebendezol'
   FROM path_zambia_etl.facility_encounter_report
   WHERE OPV0 IS NOT NULL
   GROUP BY zeir_id, person_id, encounter_date, child_weight, gender, dob, mother_id, child_hiv_expo, child_weighed,
     BCG1, OPV0, OPV1, PCV1, Penta1, Rota1, OPV2, PCV2, Penta2, Rota2,
     OPV3, PCV3, Penta3, Measles1, MR1, OPV4, Measles2, MR2, BCG2, vitamin_a, mebendezol)

  UNION

  (SELECT
     max(encounter_id)  AS 'Encounter ID',
     encounter_date     AS 'Encounter Date',
     person_id,
     zeir_id            AS 'ZEIR ID',
     gender             AS 'Gender',
     dob                AS 'Date of Birth',
     mother_id          AS 'Mother ID',
     child_hiv_expo     AS 'Child HIV Exposure',
     max(fac_id)        AS 'Facility ID',
     max(fac_name)      AS 'Facility Name',
     max(district_id)   AS 'District ID',
     max(district_name) AS 'District Name',
     max(province_id)   AS 'Province ID',
     max(province_name) AS 'Province Name',
     max(provider_id)   AS 'Provider ID',
     max(provider_name) AS 'Provider Name',
     child_weighed      AS ' Child Weighed',
     child_weight       AS 'Child Weight',
     max(z_score)       AS 'Z-score',
     BCG1,
     OPV0,
     OPV1,
     PCV1,
     Penta1             AS 'Penta 1',
     Rota1              AS 'Rota 1',
     OPV2,
     PCV2,
     Penta2             AS 'Penta2',
     Rota2              AS 'Rota 2',
     OPV3,
     PCV3,
     Penta3             AS 'Penta 3',
     Measles1           AS 'Measles 1',
     MR1,
     OPV4,
     Measles2           AS 'Measles 2',
     MR2,
     BCG2,
     vitamin_a          AS 'Vitamin A',
     mebendezol         AS 'Mebendezol'
   FROM path_zambia_etl.facility_encounter_report
   WHERE OPV1 IS NOT NULL
   GROUP BY zeir_id, person_id, encounter_date, child_weight, gender, dob, mother_id, child_hiv_expo, child_weighed,
     BCG1, OPV0, OPV1, PCV1, Penta1, Rota1, OPV2, PCV2, Penta2, Rota2,
     OPV3, PCV3, Penta3, Measles1, MR1, OPV4, Measles2, MR2, BCG2, vitamin_a, mebendezol)

  UNION


  (SELECT
     max(encounter_id)  AS 'Encounter ID',
     encounter_date     AS 'Encounter Date',
     person_id,
     zeir_id            AS 'ZEIR ID',
     gender             AS 'Gender',
     dob                AS 'Date of Birth',
     mother_id          AS 'Mother ID',
     child_hiv_expo     AS 'Child HIV Exposure',
     max(fac_id)        AS 'Facility ID',
     max(fac_name)      AS 'Facility Name',
     max(district_id)   AS 'District ID',
     max(district_name) AS 'District Name',
     max(province_id)   AS 'Province ID',
     max(province_name) AS 'Province Name',
     max(provider_id)   AS 'Provider ID',
     max(provider_name) AS 'Provider Name',
     child_weighed      AS ' Child Weighed',
     child_weight       AS 'Child Weight',
     max(z_score)       AS 'Z-score',
     BCG1,
     OPV0,
     OPV1,
     PCV1,
     Penta1             AS 'Penta 1',
     Rota1              AS 'Rota 1',
     OPV2,
     PCV2,
     Penta2             AS 'Penta2',
     Rota2              AS 'Rota 2',
     OPV3,
     PCV3,
     Penta3             AS 'Penta 3',
     Measles1           AS 'Measles 1',
     MR1,
     OPV4,
     Measles2           AS 'Measles 2',
     MR2,
     BCG2,
     vitamin_a          AS 'Vitamin A',
     mebendezol         AS 'Mebendezol'
   FROM path_zambia_etl.facility_encounter_report
   WHERE PCV1 IS NOT NULL
   GROUP BY zeir_id, person_id, encounter_date, child_weight, gender, dob, mother_id, child_hiv_expo, child_weighed,
     BCG1, OPV0, OPV1, PCV1, Penta1, Rota1, OPV2, PCV2, Penta2, Rota2,
     OPV3, PCV3, Penta3, Measles1, MR1, OPV4, Measles2, MR2, BCG2, vitamin_a, mebendezol)

  UNION

  (SELECT
     max(encounter_id)  AS 'Encounter ID',
     encounter_date     AS 'Encounter Date',
     person_id,
     zeir_id            AS 'ZEIR ID',
     gender             AS 'Gender',
     dob                AS 'Date of Birth',
     mother_id          AS 'Mother ID',
     child_hiv_expo     AS 'Child HIV Exposure',
     max(fac_id)        AS 'Facility ID',
     max(fac_name)      AS 'Facility Name',
     max(district_id)   AS 'District ID',
     max(district_name) AS 'District Name',
     max(province_id)   AS 'Province ID',
     max(province_name) AS 'Province Name',
     max(provider_id)   AS 'Provider ID',
     max(provider_name) AS 'Provider Name',
     child_weighed      AS ' Child Weighed',
     child_weight       AS 'Child Weight',
     max(z_score)       AS 'Z-score',
     BCG1,
     OPV0,
     OPV1,
     PCV1,
     Penta1             AS 'Penta 1',
     Rota1              AS 'Rota 1',
     OPV2,
     PCV2,
     Penta2             AS 'Penta2',
     Rota2              AS 'Rota 2',
     OPV3,
     PCV3,
     Penta3             AS 'Penta 3',
     Measles1           AS 'Measles 1',
     MR1,
     OPV4,
     Measles2           AS 'Measles 2',
     MR2,
     BCG2,
     vitamin_a          AS 'Vitamin A',
     mebendezol         AS 'Mebendezol'
   FROM path_zambia_etl.facility_encounter_report
   WHERE Penta1 IS NOT NULL
   GROUP BY zeir_id, person_id, encounter_date, child_weight, gender, dob, mother_id, child_hiv_expo, child_weighed,
     BCG1, OPV0, OPV1, PCV1, Penta1, Rota1, OPV2, PCV2, Penta2, Rota2,
     OPV3, PCV3, Penta3, Measles1, MR1, OPV4, Measles2, MR2, BCG2, vitamin_a, mebendezol)

  UNION
  (SELECT max(encounter_id) as 'Encounter ID',
          encounter_date as 'Encounter Date',
     person_id,
          zeir_id as 'ZEIR ID',
          gender as 'Gender',
          dob as 'Date of Birth',
          mother_id as 'Mother ID',
          child_hiv_expo as 'Child HIV Exposure',
          max(fac_id) as 'Facility ID',
          max(fac_name) as 'Facility Name',
          max(district_id) as 'District ID',
          max(district_name) as 'District Name',
          max(province_id) as 'Province ID',
          max(province_name) as 'Province Name',
          max(provider_id) as 'Provider ID',
          max(provider_name) as 'Provider Name',
          child_weighed as ' Child Weighed',
          child_weight as 'Child Weight',
          max(z_score) as 'Z-score',
     BCG1,
     OPV0,
     OPV1,
     PCV1,
          Penta1 as 'Penta 1',
          Rota1 as 'Rota 1',
     OPV2,
     PCV2,
          Penta2 as 'Penta2',
          Rota2 as 'Rota 2',
     OPV3,
     PCV3,
          Penta3 as 'Penta 3',
          Measles1 as 'Measles 1',
     MR1,
     OPV4,
          Measles2 as 'Measles 2',
     MR2,
     BCG2,
          vitamin_a as 'Vitamin A',
          mebendezol as 'Mebendezol'
   FROM path_zambia_etl.facility_encounter_report where  Rota1 is not null
   group by zeir_id, person_id, encounter_date, child_weight, gender, dob,mother_id,child_hiv_expo,  child_weighed,
     BCG1,OPV0,OPV1,PCV1,Penta1,Rota1 ,OPV2,PCV2,Penta2,Rota2,
     OPV3,PCV3,Penta3,Measles1 ,MR1,OPV4,Measles2,MR2,BCG2,vitamin_a,mebendezol)

  UNION
  (SELECT max(encounter_id) as 'Encounter ID',
          encounter_date as 'Encounter Date',
     person_id,
          zeir_id as 'ZEIR ID',
          gender as 'Gender',
          dob as 'Date of Birth',
          mother_id as 'Mother ID',
          child_hiv_expo as 'Child HIV Exposure',
          max(fac_id) as 'Facility ID',
          max(fac_name) as 'Facility Name',
          max(district_id) as 'District ID',
          max(district_name) as 'District Name',
          max(province_id) as 'Province ID',
          max(province_name) as 'Province Name',
          max(provider_id) as 'Provider ID',
          max(provider_name) as 'Provider Name',
          child_weighed as ' Child Weighed',
          child_weight as 'Child Weight',
          max(z_score) as 'Z-score',
     BCG1,
     OPV0,
     OPV1,
     PCV1,
          Penta1 as 'Penta 1',
          Rota1 as 'Rota 1',
     OPV2,
     PCV2,
          Penta2 as 'Penta2',
          Rota2 as 'Rota 2',
     OPV3,
     PCV3,
          Penta3 as 'Penta 3',
          Measles1 as 'Measles 1',
     MR1,
     OPV4,
          Measles2 as 'Measles 2',
     MR2,
     BCG2,
          vitamin_a as 'Vitamin A',
          mebendezol as 'Mebendezol'
   FROM path_zambia_etl.facility_encounter_report where  OPV2 is not null
   group by zeir_id, person_id, encounter_date, child_weight, gender, dob,mother_id,child_hiv_expo,  child_weighed,
     BCG1,OPV0,OPV1,PCV1,Penta1,Rota1 ,OPV2,PCV2,Penta2,Rota2,
     OPV3,PCV3,Penta3,Measles1 ,MR1,OPV4,Measles2,MR2,BCG2,vitamin_a,mebendezol)

  UNION
  (SELECT max(encounter_id) as 'Encounter ID',
          encounter_date as 'Encounter Date',
     person_id,
          zeir_id as 'ZEIR ID',
          gender as 'Gender',
          dob as 'Date of Birth',
          mother_id as 'Mother ID',
          child_hiv_expo as 'Child HIV Exposure',
          max(fac_id) as 'Facility ID',
          max(fac_name) as 'Facility Name',
          max(district_id) as 'District ID',
          max(district_name) as 'District Name',
          max(province_id) as 'Province ID',
          max(province_name) as 'Province Name',
          max(provider_id) as 'Provider ID',
          max(provider_name) as 'Provider Name',
          child_weighed as ' Child Weighed',
          child_weight as 'Child Weight',
          max(z_score) as 'Z-score',
     BCG1,
     OPV0,
     OPV1,
     PCV1,
          Penta1 as 'Penta 1',
          Rota1 as 'Rota 1',
     OPV2,
     PCV2,
          Penta2 as 'Penta2',
          Rota2 as 'Rota 2',
     OPV3,
     PCV3,
          Penta3 as 'Penta 3',
          Measles1 as 'Measles 1',
     MR1,
     OPV4,
          Measles2 as 'Measles 2',
     MR2,
     BCG2,
          vitamin_a as 'Vitamin A',
          mebendezol as 'Mebendezol'
   FROM path_zambia_etl.facility_encounter_report where  PCV2 is not null
   group by zeir_id, person_id, encounter_date, child_weight, gender, dob,mother_id,child_hiv_expo,  child_weighed,
     BCG1,OPV0,OPV1,PCV1,Penta1,Rota1 ,OPV2,PCV2,Penta2,Rota2,
     OPV3,PCV3,Penta3,Measles1 ,MR1,OPV4,Measles2,MR2,BCG2,vitamin_a,mebendezol)

  UNION
  (SELECT max(encounter_id) as 'Encounter ID',
          encounter_date as 'Encounter Date',
     person_id,
          zeir_id as 'ZEIR ID',
          gender as 'Gender',
          dob as 'Date of Birth',
          mother_id as 'Mother ID',
          child_hiv_expo as 'Child HIV Exposure',
          max(fac_id) as 'Facility ID',
          max(fac_name) as 'Facility Name',
          max(district_id) as 'District ID',
          max(district_name) as 'District Name',
          max(province_id) as 'Province ID',
          max(province_name) as 'Province Name',
          max(provider_id) as 'Provider ID',
          max(provider_name) as 'Provider Name',
          child_weighed as ' Child Weighed',
          child_weight as 'Child Weight',
          max(z_score) as 'Z-score',
     BCG1,
     OPV0,
     OPV1,
     PCV1,
          Penta1 as 'Penta 1',
          Rota1 as 'Rota 1',
     OPV2,
     PCV2,
          Penta2 as 'Penta2',
          Rota2 as 'Rota 2',
     OPV3,
     PCV3,
          Penta3 as 'Penta 3',
          Measles1 as 'Measles 1',
     MR1,
     OPV4,
          Measles2 as 'Measles 2',
     MR2,
     BCG2,
          vitamin_a as 'Vitamin A',
          mebendezol as 'Mebendezol'
   FROM path_zambia_etl.facility_encounter_report where  Penta2 is not null
   group by zeir_id, person_id, encounter_date, child_weight, gender, dob,mother_id,child_hiv_expo,  child_weighed,
     BCG1,OPV0,OPV1,PCV1,Penta1,Rota1 ,OPV2,PCV2,Penta2,Rota2,
     OPV3,PCV3,Penta3,Measles1 ,MR1,OPV4,Measles2,MR2,BCG2,vitamin_a,mebendezol)

  UNION
  (SELECT max(encounter_id) as 'Encounter ID',
          encounter_date as 'Encounter Date',
     person_id,
          zeir_id as 'ZEIR ID',
          gender as 'Gender',
          dob as 'Date of Birth',
          mother_id as 'Mother ID',
          child_hiv_expo as 'Child HIV Exposure',
          max(fac_id) as 'Facility ID',
          max(fac_name) as 'Facility Name',
          max(district_id) as 'District ID',
          max(district_name) as 'District Name',
          max(province_id) as 'Province ID',
          max(province_name) as 'Province Name',
          max(provider_id) as 'Provider ID',
          max(provider_name) as 'Provider Name',
          child_weighed as ' Child Weighed',
          child_weight as 'Child Weight',
          max(z_score) as 'Z-score',
     BCG1,
     OPV0,
     OPV1,
     PCV1,
          Penta1 as 'Penta 1',
          Rota1 as 'Rota 1',
     OPV2,
     PCV2,
          Penta2 as 'Penta2',
          Rota2 as 'Rota 2',
     OPV3,
     PCV3,
          Penta3 as 'Penta 3',
          Measles1 as 'Measles 1',
     MR1,
     OPV4,
          Measles2 as 'Measles 2',
     MR2,
     BCG2,
          vitamin_a as 'Vitamin A',
          mebendezol as 'Mebendezol'
   FROM path_zambia_etl.facility_encounter_report where  Rota2 is not null
   group by zeir_id, person_id, encounter_date, child_weight, gender, dob,mother_id,child_hiv_expo,  child_weighed,
     BCG1,OPV0,OPV1,PCV1,Penta1,Rota1 ,OPV2,PCV2,Penta2,Rota2,
     OPV3,PCV3,Penta3,Measles1 ,MR1,OPV4,Measles2,MR2,BCG2,vitamin_a,mebendezol)

  UNION
  (SELECT max(encounter_id) as 'Encounter ID',
          encounter_date as 'Encounter Date',
     person_id,
          zeir_id as 'ZEIR ID',
          gender as 'Gender',
          dob as 'Date of Birth',
          mother_id as 'Mother ID',
          child_hiv_expo as 'Child HIV Exposure',
          max(fac_id) as 'Facility ID',
          max(fac_name) as 'Facility Name',
          max(district_id) as 'District ID',
          max(district_name) as 'District Name',
          max(province_id) as 'Province ID',
          max(province_name) as 'Province Name',
          max(provider_id) as 'Provider ID',
          max(provider_name) as 'Provider Name',
          child_weighed as ' Child Weighed',
          child_weight as 'Child Weight',
          max(z_score) as 'Z-score',
     BCG1,
     OPV0,
     OPV1,
     PCV1,
          Penta1 as 'Penta 1',
          Rota1 as 'Rota 1',
     OPV2,
     PCV2,
          Penta2 as 'Penta2',
          Rota2 as 'Rota 2',
     OPV3,
     PCV3,
          Penta3 as 'Penta 3',
          Measles1 as 'Measles 1',
     MR1,
     OPV4,
          Measles2 as 'Measles 2',
     MR2,
     BCG2,
          vitamin_a as 'Vitamin A',
          mebendezol as 'Mebendezol'
   FROM path_zambia_etl.facility_encounter_report where  OPV3 is not null
   group by zeir_id, person_id, encounter_date, child_weight, gender, dob,mother_id,child_hiv_expo,  child_weighed,
     BCG1,OPV0,OPV1,PCV1,Penta1,Rota1 ,OPV2,PCV2,Penta2,Rota2,
     OPV3,PCV3,Penta3,Measles1 ,MR1,OPV4,Measles2,MR2,BCG2,vitamin_a,mebendezol)

  UNION
  (SELECT max(encounter_id) as 'Encounter ID',
          encounter_date as 'Encounter Date',
     person_id,
          zeir_id as 'ZEIR ID',
          gender as 'Gender',
          dob as 'Date of Birth',
          mother_id as 'Mother ID',
          child_hiv_expo as 'Child HIV Exposure',
          max(fac_id) as 'Facility ID',
          max(fac_name) as 'Facility Name',
          max(district_id) as 'District ID',
          max(district_name) as 'District Name',
          max(province_id) as 'Province ID',
          max(province_name) as 'Province Name',
          max(provider_id) as 'Provider ID',
          max(provider_name) as 'Provider Name',
          child_weighed as ' Child Weighed',
          child_weight as 'Child Weight',
          max(z_score) as 'Z-score',
     BCG1,
     OPV0,
     OPV1,
     PCV1,
          Penta1 as 'Penta 1',
          Rota1 as 'Rota 1',
     OPV2,
     PCV2,
          Penta2 as 'Penta2',
          Rota2 as 'Rota 2',
     OPV3,
     PCV3,
          Penta3 as 'Penta 3',
          Measles1 as 'Measles 1',
     MR1,
     OPV4,
          Measles2 as 'Measles 2',
     MR2,
     BCG2,
          vitamin_a as 'Vitamin A',
          mebendezol as 'Mebendezol'
   FROM path_zambia_etl.facility_encounter_report where  PCV3 is not null
   group by zeir_id, person_id, encounter_date, child_weight, gender, dob,mother_id,child_hiv_expo,  child_weighed,
     BCG1,OPV0,OPV1,PCV1,Penta1,Rota1 ,OPV2,PCV2,Penta2,Rota2,
     OPV3,PCV3,Penta3,Measles1 ,MR1,OPV4,Measles2,MR2,BCG2,vitamin_a,mebendezol)

  UNION
  (SELECT max(encounter_id) as 'Encounter ID',
          encounter_date as 'Encounter Date',
     person_id,
          zeir_id as 'ZEIR ID',
          gender as 'Gender',
          dob as 'Date of Birth',
          mother_id as 'Mother ID',
          child_hiv_expo as 'Child HIV Exposure',
          max(fac_id) as 'Facility ID',
          max(fac_name) as 'Facility Name',
          max(district_id) as 'District ID',
          max(district_name) as 'District Name',
          max(province_id) as 'Province ID',
          max(province_name) as 'Province Name',
          max(provider_id) as 'Provider ID',
          max(provider_name) as 'Provider Name',
          child_weighed as ' Child Weighed',
          child_weight as 'Child Weight',
          max(z_score) as 'Z-score',
     BCG1,
     OPV0,
     OPV1,
     PCV1,
          Penta1 as 'Penta 1',
          Rota1 as 'Rota 1',
     OPV2,
     PCV2,
          Penta2 as 'Penta2',
          Rota2 as 'Rota 2',
     OPV3,
     PCV3,
          Penta3 as 'Penta 3',
          Measles1 as 'Measles 1',
     MR1,
     OPV4,
          Measles2 as 'Measles 2',
     MR2,
     BCG2,
          vitamin_a as 'Vitamin A',
          mebendezol as 'Mebendezol'
   FROM path_zambia_etl.facility_encounter_report where  Penta3 is not null
   group by zeir_id, person_id, encounter_date, child_weight, gender, dob,mother_id,child_hiv_expo,  child_weighed,
     BCG1,OPV0,OPV1,PCV1,Penta1,Rota1 ,OPV2,PCV2,Penta2,Rota2,
     OPV3,PCV3,Penta3,Measles1 ,MR1,OPV4,Measles2,MR2,BCG2,vitamin_a,mebendezol)

  UNION
  (SELECT max(encounter_id) as 'Encounter ID',
          encounter_date as 'Encounter Date',
     person_id,
          zeir_id as 'ZEIR ID',
          gender as 'Gender',
          dob as 'Date of Birth',
          mother_id as 'Mother ID',
          child_hiv_expo as 'Child HIV Exposure',
          max(fac_id) as 'Facility ID',
          max(fac_name) as 'Facility Name',
          max(district_id) as 'District ID',
          max(district_name) as 'District Name',
          max(province_id) as 'Province ID',
          max(province_name) as 'Province Name',
          max(provider_id) as 'Provider ID',
          max(provider_name) as 'Provider Name',
          child_weighed as ' Child Weighed',
          child_weight as 'Child Weight',
          max(z_score) as 'Z-score',
     BCG1,
     OPV0,
     OPV1,
     PCV1,
          Penta1 as 'Penta 1',
          Rota1 as 'Rota 1',
     OPV2,
     PCV2,
          Penta2 as 'Penta2',
          Rota2 as 'Rota 2',
     OPV3,
     PCV3,
          Penta3 as 'Penta 3',
          Measles1 as 'Measles 1',
     MR1,
     OPV4,
          Measles2 as 'Measles 2',
     MR2,
     BCG2,
          vitamin_a as 'Vitamin A',
          mebendezol as 'Mebendezol'
   FROM path_zambia_etl.facility_encounter_report where  Measles1 is not null
   group by zeir_id, person_id, encounter_date, child_weight, gender, dob,mother_id,child_hiv_expo,  child_weighed,
     BCG1,OPV0,OPV1,PCV1,Penta1,Rota1 ,OPV2,PCV2,Penta2,Rota2,
     OPV3,PCV3,Penta3,Measles1 ,MR1,OPV4,Measles2,MR2,BCG2,vitamin_a,mebendezol)

  UNION
  (SELECT max(encounter_id) as 'Encounter ID',
          encounter_date as 'Encounter Date',
     person_id,
          zeir_id as 'ZEIR ID',
          gender as 'Gender',
          dob as 'Date of Birth',
          mother_id as 'Mother ID',
          child_hiv_expo as 'Child HIV Exposure',
          max(fac_id) as 'Facility ID',
          max(fac_name) as 'Facility Name',
          max(district_id) as 'District ID',
          max(district_name) as 'District Name',
          max(province_id) as 'Province ID',
          max(province_name) as 'Province Name',
          max(provider_id) as 'Provider ID',
          max(provider_name) as 'Provider Name',
          child_weighed as ' Child Weighed',
          child_weight as 'Child Weight',
          max(z_score) as 'Z-score',
     BCG1,
     OPV0,
     OPV1,
     PCV1,
          Penta1 as 'Penta 1',
          Rota1 as 'Rota 1',
     OPV2,
     PCV2,
          Penta2 as 'Penta2',
          Rota2 as 'Rota 2',
     OPV3,
     PCV3,
          Penta3 as 'Penta 3',
          Measles1 as 'Measles 1',
     MR1,
     OPV4,
          Measles2 as 'Measles 2',
     MR2,
     BCG2,
          vitamin_a as 'Vitamin A',
          mebendezol as 'Mebendezol'
   FROM path_zambia_etl.facility_encounter_report where  MR1 is not null
   group by zeir_id, person_id, encounter_date, child_weight, gender, dob,mother_id,child_hiv_expo,  child_weighed,
     BCG1,OPV0,OPV1,PCV1,Penta1,Rota1 ,OPV2,PCV2,Penta2,Rota2,
     OPV3,PCV3,Penta3,Measles1 ,MR1,OPV4,Measles2,MR2,BCG2,vitamin_a,mebendezol)

  UNION
  (SELECT max(encounter_id) as 'Encounter ID',
          encounter_date as 'Encounter Date',
     person_id,
          zeir_id as 'ZEIR ID',
          gender as 'Gender',
          dob as 'Date of Birth',
          mother_id as 'Mother ID',
          child_hiv_expo as 'Child HIV Exposure',
          max(fac_id) as 'Facility ID',
          max(fac_name) as 'Facility Name',
          max(district_id) as 'District ID',
          max(district_name) as 'District Name',
          max(province_id) as 'Province ID',
          max(province_name) as 'Province Name',
          max(provider_id) as 'Provider ID',
          max(provider_name) as 'Provider Name',
          child_weighed as ' Child Weighed',
          child_weight as 'Child Weight',
          max(z_score) as 'Z-score',
     BCG1,
     OPV0,
     OPV1,
     PCV1,
          Penta1 as 'Penta 1',
          Rota1 as 'Rota 1',
     OPV2,
     PCV2,
          Penta2 as 'Penta2',
          Rota2 as 'Rota 2',
     OPV3,
     PCV3,
          Penta3 as 'Penta 3',
          Measles1 as 'Measles 1',
     MR1,
     OPV4,
          Measles2 as 'Measles 2',
     MR2,
     BCG2,
          vitamin_a as 'Vitamin A',
          mebendezol as 'Mebendezol'
   FROM path_zambia_etl.facility_encounter_report where  OPV4 is not null
   group by zeir_id, person_id, encounter_date, child_weight, gender, dob,mother_id,child_hiv_expo,  child_weighed,
     BCG1,OPV0,OPV1,PCV1,Penta1,Rota1 ,OPV2,PCV2,Penta2,Rota2,
     OPV3,PCV3,Penta3,Measles1 ,MR1,OPV4,Measles2,MR2,BCG2,vitamin_a,mebendezol)

  UNION
  (SELECT max(encounter_id) as 'Encounter ID',
          encounter_date as 'Encounter Date',
     person_id,
          zeir_id as 'ZEIR ID',
          gender as 'Gender',
          dob as 'Date of Birth',
          mother_id as 'Mother ID',
          child_hiv_expo as 'Child HIV Exposure',
          max(fac_id) as 'Facility ID',
          max(fac_name) as 'Facility Name',
          max(district_id) as 'District ID',
          max(district_name) as 'District Name',
          max(province_id) as 'Province ID',
          max(province_name) as 'Province Name',
          max(provider_id) as 'Provider ID',
          max(provider_name) as 'Provider Name',
          child_weighed as ' Child Weighed',
          child_weight as 'Child Weight',
          max(z_score) as 'Z-score',
     BCG1,
     OPV0,
     OPV1,
     PCV1,
          Penta1 as 'Penta 1',
          Rota1 as 'Rota 1',
     OPV2,
     PCV2,
          Penta2 as 'Penta2',
          Rota2 as 'Rota 2',
     OPV3,
     PCV3,
          Penta3 as 'Penta 3',
          Measles1 as 'Measles 1',
     MR1,
     OPV4,
          Measles2 as 'Measles 2',
     MR2,
     BCG2,
          vitamin_a as 'Vitamin A',
          mebendezol as 'Mebendezol'
   FROM path_zambia_etl.facility_encounter_report where  Measles2 is not null
   group by zeir_id, person_id, encounter_date, child_weight, gender, dob,mother_id,child_hiv_expo,  child_weighed,
     BCG1,OPV0,OPV1,PCV1,Penta1,Rota1 ,OPV2,PCV2,Penta2,Rota2,
     OPV3,PCV3,Penta3,Measles1 ,MR1,OPV4,Measles2,MR2,BCG2,vitamin_a,mebendezol)

  UNION
  (SELECT max(encounter_id) as 'Encounter ID',
          encounter_date as 'Encounter Date',
     person_id,
          zeir_id as 'ZEIR ID',
          gender as 'Gender',
          dob as 'Date of Birth',
          mother_id as 'Mother ID',
          child_hiv_expo as 'Child HIV Exposure',
          max(fac_id) as 'Facility ID',
          max(fac_name) as 'Facility Name',
          max(district_id) as 'District ID',
          max(district_name) as 'District Name',
          max(province_id) as 'Province ID',
          max(province_name) as 'Province Name',
          max(provider_id) as 'Provider ID',
          max(provider_name) as 'Provider Name',
          child_weighed as ' Child Weighed',
          child_weight as 'Child Weight',
          max(z_score) as 'Z-score',
     BCG1,
     OPV0,
     OPV1,
     PCV1,
          Penta1 as 'Penta 1',
          Rota1 as 'Rota 1',
     OPV2,
     PCV2,
          Penta2 as 'Penta2',
          Rota2 as 'Rota 2',
     OPV3,
     PCV3,
          Penta3 as 'Penta 3',
          Measles1 as 'Measles 1',
     MR1,
     OPV4,
          Measles2 as 'Measles 2',
     MR2,
     BCG2,
          vitamin_a as 'Vitamin A',
          mebendezol as 'Mebendezol'
   FROM path_zambia_etl.facility_encounter_report where  MR2 is not null
   group by zeir_id, person_id, encounter_date, child_weight, gender, dob,mother_id,child_hiv_expo,  child_weighed,
     BCG1,OPV0,OPV1,PCV1,Penta1,Rota1 ,OPV2,PCV2,Penta2,Rota2,
     OPV3,PCV3,Penta3,Measles1 ,MR1,OPV4,Measles2,MR2,BCG2,vitamin_a,mebendezol)

  UNION
  (SELECT max(encounter_id) as 'Encounter ID',
          encounter_date as 'Encounter Date',
     person_id,
          zeir_id as 'ZEIR ID',
          gender as 'Gender',
          dob as 'Date of Birth',
          mother_id as 'Mother ID',
          child_hiv_expo as 'Child HIV Exposure',
          max(fac_id) as 'Facility ID',
          max(fac_name) as 'Facility Name',
          max(district_id) as 'District ID',
          max(district_name) as 'District Name',
          max(province_id) as 'Province ID',
          max(province_name) as 'Province Name',
          max(provider_id) as 'Provider ID',
          max(provider_name) as 'Provider Name',
          child_weighed as ' Child Weighed',
          child_weight as 'Child Weight',
          max(z_score) as 'Z-score',
     BCG1,
     OPV0,
     OPV1,
     PCV1,
          Penta1 as 'Penta 1',
          Rota1 as 'Rota 1',
     OPV2,
     PCV2,
          Penta2 as 'Penta2',
          Rota2 as 'Rota 2',
     OPV3,
     PCV3,
          Penta3 as 'Penta 3',
          Measles1 as 'Measles 1',
     MR1,
     OPV4,
          Measles2 as 'Measles 2',
     MR2,
     BCG2,
          vitamin_a as 'Vitamin A',
          mebendezol as 'Mebendezol'
   FROM path_zambia_etl.facility_encounter_report where  BCG2 is not null
   group by zeir_id, person_id, encounter_date, child_weight, gender, dob,mother_id,child_hiv_expo,  child_weighed,
     BCG1,OPV0,OPV1,PCV1,Penta1,Rota1 ,OPV2,PCV2,Penta2,Rota2,
     OPV3,PCV3,Penta3,Measles1 ,MR1,OPV4,Measles2,MR2,BCG2,vitamin_a,mebendezol)

  UNION
  (SELECT max(encounter_id) as 'Encounter ID',
          encounter_date as 'Encounter Date',
     person_id,
          zeir_id as 'ZEIR ID',
          gender as 'Gender',
          dob as 'Date of Birth',
          mother_id as 'Mother ID',
          child_hiv_expo as 'Child HIV Exposure',
          max(fac_id) as 'Facility ID',
          max(fac_name) as 'Facility Name',
          max(district_id) as 'District ID',
          max(district_name) as 'District Name',
          max(province_id) as 'Province ID',
          max(province_name) as 'Province Name',
          max(provider_id) as 'Provider ID',
          max(provider_name) as 'Provider Name',
          child_weighed as ' Child Weighed',
          child_weight as 'Child Weight',
          max(z_score) as 'Z-score',
     BCG1,
     OPV0,
     OPV1,
     PCV1,
          Penta1 as 'Penta 1',
          Rota1 as 'Rota 1',
     OPV2,
     PCV2,
          Penta2 as 'Penta2',
          Rota2 as 'Rota 2',
     OPV3,
     PCV3,
          Penta3 as 'Penta 3',
          Measles1 as 'Measles 1',
     MR1,
     OPV4,
          Measles2 as 'Measles 2',
     MR2,
     BCG2,
          vitamin_a as 'Vitamin A',
          mebendezol as 'Mebendezol'
   FROM path_zambia_etl.facility_encounter_report where  vitamin_a is not null
   group by zeir_id, person_id, encounter_date, child_weight, gender, dob,mother_id,child_hiv_expo,  child_weighed,
     BCG1,OPV0,OPV1,PCV1,Penta1,Rota1 ,OPV2,PCV2,Penta2,Rota2,
     OPV3,PCV3,Penta3,Measles1 ,MR1,OPV4,Measles2,MR2,BCG2,vitamin_a,mebendezol)

  UNION
  (SELECT max(encounter_id) as 'Encounter ID',
          encounter_date as 'Encounter Date',
     person_id,
          zeir_id as 'ZEIR ID',
          gender as 'Gender',
          dob as 'Date of Birth',
          mother_id as 'Mother ID',
          child_hiv_expo as 'Child HIV Exposure',
          max(fac_id) as 'Facility ID',
          max(fac_name) as 'Facility Name',
          max(district_id) as 'District ID',
          max(district_name) as 'District Name',
          max(province_id) as 'Province ID',
          max(province_name) as 'Province Name',
          max(provider_id) as 'Provider ID',
          max(provider_name) as 'Provider Name',
          child_weighed as ' Child Weighed',
          child_weight as 'Child Weight',
          max(z_score) as 'Z-score',
     BCG1,
     OPV0,
     OPV1,
     PCV1,
          Penta1 as 'Penta 1',
          Rota1 as 'Rota 1',
     OPV2,
     PCV2,
          Penta2 as 'Penta2',
          Rota2 as 'Rota 2',
     OPV3,
     PCV3,
          Penta3 as 'Penta 3',
          Measles1 as 'Measles 1',
     MR1,
     OPV4,
          Measles2 as 'Measles 2',
     MR2,
     BCG2,
          vitamin_a as 'Vitamin A',
          mebendezol as 'Mebendezol'
   FROM path_zambia_etl.facility_encounter_report where  mebendezol is not null
   group by zeir_id, person_id, encounter_date, child_weight, gender, dob,mother_id,child_hiv_expo,  child_weighed,
     BCG1,OPV0,OPV1,PCV1,Penta1,Rota1 ,OPV2,PCV2,Penta2,Rota2,
     OPV3,PCV3,Penta3,Measles1 ,MR1,OPV4,Measles2,MR2,BCG2,vitamin_a,mebendezol ) order by 1;
